
services:
  full_node:
    image: blockdagnetwork/awakening:v0.0.3
    container_name: blockdag-full-testnet
    restart: unless-stopped
    ports:
      - "38131:38131"
      - "18545:18545"
      - "18546:18546"
      - "18150:18150"
    volumes:
      - bdag_bin:/opt/bdag
      - ./bin/bdag/data:/bdag/data
      - ./bin/bdag/logs:/bdag/logs
    environment:
      NODE_ARGS: >-
        --testnet --rpclisten=0.0.0.0:38131 --notls --rpcuser=test --rpcpass=test
        --walletpass=test
        --evmenv="--http --http.port=18545 --http.addr=0.0.0.0
        --http.api=net,web3,eth,bdag,txpool,debug --allow-insecure-unlock --ws
        --ws.addr=0.0.0.0 --ws.port=18546 --rpc.allow-unprotected-txs --gcmode=archive"
        --datadir=/bdag/data
        --addpeer=/ip4/13.245.135.249/tcp/18150/p2p/16Uiu2HAm3hjo65MZvBEJuVASMoSDsXfMzC8m2ZEAeK8CjjJkRvf9
      RPC_URL: ws://127.0.0.1:18546
      CONTRACT_ADDRESS: 0x96C22c86B91235165eBF1F0f41FbeadA9C323A7A
      ROLLOUT_WINDOW: 30m
      CONTRACT_DEPLOY_BLOCK: 257509
      HEALTH_MIN_PEERS: 1

volumes:
  bdag_bin: {}